# Generated by Django 4.2.27 on 2025-12-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Положительная сумма выплаты в валюте платежа.', max_digits=12, verbose_name='Сумма выплаты'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(help_text='Трёхбуквенный код валюты (ISO 4217), например USD.', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительный комментарий к заявке.', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='recipient_details',
            field=models.JSONField(help_text='Номер счёта, номер карты или иные данные получателя.', verbose_name='Реквизиты получателя'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('processing', 'Обрабатывается'), ('completed', 'Выполнена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='created', help_text='Текущий статус обработки заявки.', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
