# Generated by Django 4.2.27 on 2025-12-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_alter_payout_amount_alter_payout_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(help_text='Трёхбуквенный код валюты (ISO 4217), например USD.', verbose_name='Валюта'),
        ),
    ]
